<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFnrz9qi\AdminKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFnrz9qi/AdminKernelProdContainer.php') {
    touch(__DIR__.'/ContainerFnrz9qi.legacy');

    return;
}

if (!\class_exists(AdminKernelProdContainer::class, false)) {
    \class_alias(\ContainerFnrz9qi\AdminKernelProdContainer::class, AdminKernelProdContainer::class, false);
}

return new \ContainerFnrz9qi\AdminKernelProdContainer([
    'container.build_hash' => 'Fnrz9qi',
    'container.build_id' => 'dff14ed5',
    'container.build_time' => 1759921015,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFnrz9qi');
